### ISSUE TITLE
Owner often forgotten after relog

### ISSUE THREAD

**Issue by Emma450** [lickx/oscollar#76]
On V9 once you set an owner it is often forgotten after logging back in after a day or two or relogging often and you have to then re-add your owner

**Comment by lickx** [comment]
OpenSim can often lose script state data like variable contents. In this case script state in attachments doesn't seem to be stored when logging off like it should. That is either a bug in your grid/sim configuration or in OpenSim itself. Try after adding an owner to detach the collar temporary to force the variable data to be stored. If that doesn't help you could add the owner in the .settings notecard by using the Save button in the settings menu (if your simulator supports osMakeNotecard functionality) or by clicking Print and then manually copy/paste the printed output in your .settings card.

The prim holding the settings card can be made visible by:
<prefix>show storage
Then you can edit linked contents and see the .settings card inside
It can be hidden again by:
<prefix>hide storage

Unfortunately this is not a bug that OsCollar can fix, it is a bigger problem in OpenSim and affects any scripted attachments not just collars. Hypergrid jumps in particular are fatal, the script will stop working on the initial jump and when entering a neighbour sim in the destination grid the script starts up blank from scratch and will have lost all script variables. That this also occurs when simply relogging is very worrying.

**Comment by Emma450** [comment]
Thank you i did what you said with printing out the settings and then manually copy and pasting it into the notecard for .settings yet when i relogged the settings where wiped out and back to how they where before :(

**Comment by lickx** [comment]
Can't reproduce your bug yet but I'll keep trying :(

Meanwhile i reverted commit cfad907 in a branch called [issue76](https://github.com/lickx/oscollar/tree/issue76). If you feel adventurious you could try replacing [oc_auth](https://raw.githubusercontent.com/lickx/oscollar/issue76/src/collar/oc_auth.lsl) and [oc_settings](https://raw.githubusercontent.com/lickx/oscollar/issue76/src/collar/oc_settings.lsl) in your collar. Always work on a copy.

**Comment by lickx** [comment]
@Emma450 which viewer where you using while this happened?

I maybe found how to reproduce this on Firestorm, when logging in to a freshly restarted sim hosted on a slow 10MBit connection. But with Cool VL Viewer everything was just fine. I was told Singularity also doesn't have this problem so it might be a regression in v3 viewers that the v1 viewers don't have.

On my fast 1GBit sim on OsGrid this isn't a problem in any viewer, that's for sure.
